#!/usr/bin/env bash

SELECTED_WORKTREE_PATH=
SELECTED_WORKTREE_NAME=

MAIN_SESSION="main"
if [[ -n $TMUX ]]; then
    MAIN_SESSION=$(tmux display-message -p '#S')
fi

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$MAIN_SESSION:$1"
    else
        tmux switch-client -t "$MAIN_SESSION:$1"
    fi
}

has_window() {
    tmux list-windows -t "$MAIN_SESSION" -F '#W' 2>/dev/null | grep -q "^$1\$"
}

hydrate() {
    if [ -f "$2/.tmux-sessionizer" ]; then
        tmux send-keys -t "$MAIN_SESSION:$1" "source $2/.tmux-sessionizer" c-M
    elif [ -f "$HOME/.tmux-sessionizer" ]; then
        tmux send-keys -t "$MAIN_SESSION:$1" "source $HOME/.tmux-sessionizer" c-M
    fi
}

session_name_component() {
    local component

    component=$(basename "$1")
    component=${component%.git}

    printf '%s\n' "$component" | tr '. ' '__'
}

project_name_for_directory() {
    local directory=$1
    local common_dir
    local common_base

    if ! git -C "$directory" rev-parse --git-dir >/dev/null 2>&1; then
        session_name_component "$directory"
        return
    fi

    common_dir=$(git -C "$directory" rev-parse --path-format=absolute --git-common-dir 2>/dev/null)
    if [[ -z $common_dir ]]; then
        common_dir=$(git -C "$directory" rev-parse --git-common-dir 2>/dev/null)
    fi

    common_base=$(basename "$common_dir")
    if [[ $common_base == ".git" ]]; then
        session_name_component "$(dirname "$common_dir")"
    else
        session_name_component "$common_dir"
    fi
}

worktree_name_from_path() {
    local worktree_path=$1
    local project_name=$2

    case $worktree_path in
        */"$project_name")
            return
            ;;
        */"$project_name"/*)
            printf '%s\n' "${worktree_path#*"/$project_name"/}"
            return
            ;;
    esac
}

session_name_for_worktree() {
    local project_name=$1
    local worktree_path=$2
    local branch_ref=$3
    local worktree_name

    worktree_name=$(worktree_name_from_path "$worktree_path" "$project_name")

    if [[ -z $worktree_name && -n $branch_ref ]]; then
        worktree_name=${branch_ref#refs/}
        worktree_name=${worktree_name#heads/}
    fi

    if [[ -z $worktree_name ]]; then
        worktree_name=$(session_name_component "$worktree_path")
    fi

    if [[ $worktree_name == "$project_name" ]]; then
        printf '%s\n' "$project_name"
        return
    fi

    printf '%s/%s\n' "$project_name" "$worktree_name"
}

session_name_for_directory() {
    local directory=$1
    local project_name
    local branch_ref

    project_name=$(project_name_for_directory "$directory")
    branch_ref=$(git -C "$directory" symbolic-ref --quiet HEAD 2>/dev/null)

    session_name_for_worktree "$project_name" "$directory" "$branch_ref"
}

worktree_label_for_worktree() {
    local project_name=$1
    local worktree_path=$2
    local branch_ref=$3
    local worktree_name

    worktree_name=$(worktree_name_from_path "$worktree_path" "$project_name")

    if [[ -z $worktree_name && -n $branch_ref ]]; then
        worktree_name=${branch_ref#refs/}
        worktree_name=${worktree_name#heads/}
    fi

    if [[ -z $worktree_name ]]; then
        worktree_name=$(session_name_component "$worktree_path")
    fi

    printf '%s\n' "$worktree_name"
}

WORKTREE_PATHS=()
WORKTREE_BRANCHES=()
WORKTREE_BARE_FLAGS=()

parse_worktree_porcelain() {
    local line
    local worktree_path=
    local branch_ref=
    local is_bare=

    WORKTREE_PATHS=()
    WORKTREE_BRANCHES=()
    WORKTREE_BARE_FLAGS=()

    while IFS= read -r line || [[ -n $line ]]; do
        if [[ -z $line ]]; then
            if [[ -n $worktree_path ]]; then
                WORKTREE_PATHS+=("$worktree_path")
                WORKTREE_BRANCHES+=("$branch_ref")
                WORKTREE_BARE_FLAGS+=("$is_bare")
            fi

            worktree_path=
            branch_ref=
            is_bare=
            continue
        fi

        case $line in
            worktree\ *)
                worktree_path=${line#worktree }
                ;;
            branch\ *)
                branch_ref=${line#branch }
                ;;
            bare)
                is_bare=1
                ;;
        esac
    done

    if [[ -n $worktree_path ]]; then
        WORKTREE_PATHS+=("$worktree_path")
        WORKTREE_BRANCHES+=("$branch_ref")
        WORKTREE_BARE_FLAGS+=("$is_bare")
    fi
}

select_worktree() {
    local directory=$1
    local canonical_directory
    local original_entry=
    local selected_worktree
    local canonical_worktree
    local worktree_path
    local branch_ref
    local is_bare
    local project_name
    local worktree_label
    local worktree_name
    local worktree_entry
    local index
    local worktree_entries=()

    SELECTED_WORKTREE_PATH=
    SELECTED_WORKTREE_NAME=

    if ! git -C "$directory" rev-parse --git-dir >/dev/null 2>&1; then
        SELECTED_WORKTREE_PATH=$directory
        SELECTED_WORKTREE_NAME=$(session_name_component "$directory")
        return
    fi

    canonical_directory=$(realpath "$directory" 2>/dev/null || printf '%s\n' "$directory")
    project_name=$(project_name_for_directory "$directory")

    parse_worktree_porcelain < <(git -C "$directory" worktree list --porcelain 2>/dev/null)

    for index in "${!WORKTREE_PATHS[@]}"; do
        worktree_path=${WORKTREE_PATHS[$index]}
        branch_ref=${WORKTREE_BRANCHES[$index]}
        is_bare=${WORKTREE_BARE_FLAGS[$index]}

        if [[ -n $is_bare ]]; then
            continue
        fi

        worktree_label=$(worktree_label_for_worktree "$project_name" "$worktree_path" "$branch_ref")
        worktree_name=$(session_name_for_worktree "$project_name" "$worktree_path" "$branch_ref")
        worktree_entry=$worktree_label$'\t'$worktree_path$'\t'$worktree_name
        canonical_worktree=$(realpath "$worktree_path" 2>/dev/null || printf '%s\n' "$worktree_path")

        if [[ $canonical_worktree == "$canonical_directory" ]]; then
            original_entry=$worktree_entry
        else
            worktree_entries+=("$worktree_entry")
        fi
    done

    if [[ -n $original_entry ]]; then
        worktree_entries+=("$original_entry")
    fi

    if (( ${#worktree_entries[@]} == 0 )); then
        SELECTED_WORKTREE_PATH=$directory
        SELECTED_WORKTREE_NAME=$(session_name_for_directory "$directory")
        return
    fi

    if (( ${#worktree_entries[@]} == 1 )); then
        selected_worktree=${worktree_entries[0]}
    else
        selected_worktree=$(printf '%s\n' "${worktree_entries[@]}" | fzf --prompt="Worktree: " --delimiter=$'\t' --with-nth=1)
    fi

    if [[ -z $selected_worktree ]]; then
        exit 0
    fi

    selected_worktree=${selected_worktree#*$'\t'}
    SELECTED_WORKTREE_PATH=${selected_worktree%%$'\t'*}
    SELECTED_WORKTREE_NAME=${selected_worktree#*$'\t'}
}

main() {
    local selected
    local selected_name
    local tmux_running
    local replace_current_pane=

    while [[ $# -gt 0 ]]; do
        case $1 in
            -c)
                replace_current_pane=1
                shift
                ;;
            *)
                selected=$1
                shift
                ;;
        esac
    done

    if [[ -z $selected ]]; then
        selected=$(find ~/.dotfiles /mnt/d/code/ /mnt/d/apps/Dropbox/ ~/Dropbox/ ~/.config ~/code/work/ ~/code/personal/ ~/Sync  -mindepth 0 -maxdepth 1 -type d | fzf)
    fi

    if [[ -z $selected ]]; then
        return
    fi

    select_worktree "$selected"

    if [[ -z $SELECTED_WORKTREE_PATH ]]; then
        return
    fi

    selected=$SELECTED_WORKTREE_PATH
    selected_name=$SELECTED_WORKTREE_NAME

    if [[ -n $replace_current_pane ]] && [[ -n $TMUX ]]; then
        tmux rename-window "$selected_name"
        tmux respawn-pane -k -c "$selected"
        hydrate "$selected_name" "$selected"
        return
    fi

    tmux_running=$(pgrep tmux)

    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        tmux new-session -d -s "$MAIN_SESSION" -n "$selected_name" -c "$selected"
        hydrate "$selected_name" "$selected"
        switch_to "$selected_name"
        return
    fi

    if ! tmux has-session -t "$MAIN_SESSION" 2>/dev/null; then
        tmux new-session -d -s "$MAIN_SESSION" -n "$selected_name" -c "$selected"
        hydrate "$selected_name" "$selected"
    elif ! has_window "$selected_name"; then
        tmux new-window -t "$MAIN_SESSION" -n "$selected_name" -c "$selected"
        hydrate "$selected_name" "$selected"
    fi

    switch_to "$selected_name"
}

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
    main "$@"
fi
